server:
  port: 8080  #端口配置
spring:
  #配置数据库
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/data-cache?useUnicode=true&useSSL=false&characterEncoding=utf8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
          username: root
          password: 1q@w3e4r
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000
            maximum-pool-size: 15
            minimum-idle: 5
  #redis参数配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 1
    timeout: 5000ms    # 连接超时时间
    lettuce:
      pool:
        max-active: 32      # 连接池最大连接数（根据并发量调整）
        max-idle: 16        # 连接池中的最大空闲连接
        min-idle: 8         # 连接池中的最小空闲连接
        max-wait: 1000ms    # 连接池最大阻塞等待时间
        time-between-eviction-runs: 10s  # 空闲连接检查间隔
      shutdown-timeout: 3s   # 关闭超时时间
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    connection-timeout: 5000ms
    cache:
      channel.size: 50
      connection.mode: channel
    requested-heartbeat: 60
    listener:
      type: simple
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 20
        prefetch: 50
        retry:
          enabled: true
          max-attempts: 5
          max-interval: 20000ms
          initial-interval: 2000ms
          multiplier: 2
          stateless: false
#日志配置
logging:
  level:
    cn.liulingfengyu: debug  #日志级别
  file:
    path: log #日志输出路径